Sar 158/feature/kids wellness
amida-tech/saraswati-cql-execution pull request #17
Opened 2021-06-23 14:50 UTC by eawest2

# Related Tickets

- [SAR-158](https://jira.amida-tech.com/browse/SAR-158)

# How Things Worked (or Didn't) Before This PR

There were no child-wellness visits for children under 15 mos.

# How Things Work Now (And How to Test)

Now there are.

You will have to run a the usual `reciver.js` in the project root, and run `yarn start` in the root as well.

Ideally you should come up with a CQL result of 4/1.

There are a large number of numerators in this document, however there is only one denominator.

# Concerns

There's a concern here, where I discovered CQL doesn't scan recursive contexts, namely EoBs. We need to scan each of the existing CQL documents to make sure they're properly configured to search through EoBs.

# Readiness

1. [ ] This PR passes all automated tests.
2. [ ] This PR has no linting errors.
3. [ ] This PR's changes to configuration files have been documented in all appropriate places (such as but not limited to README.md), if applicable.

2021-06-28 19:29 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +	and AgeInMonthsAt(end of "Measurement Period")<= 15
The HEDIS spec says "children who turn 15 months old **during the measurement year.** calculate the 15-month birthday plus 90 days". The measurement year is 2020. In this CQL you're saying that children who turn any month as long as is less than or equal to 15 should be included/ are eligible. This is incorrect in my opinion, we should either follow the calculation strategy stated or maybe do something like `AgeInMonthsAt(during "Measurement Period") == 15` if that works (IDK)

2021-06-28 19:53 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +    where AgeInMonthsAt(E0.period.end) > 15
Should this be `< 15` ?

2021-06-28 19:55 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +    without [Encounter: "Primary Care Provider"] E1
Should this be `with` instead of `without` since "the well-child visit must occur **with** a PCP"?

2021-06-29 13:06 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +		//)
I think this can all be deleted if we don't need it

2021-06-29 13:08 UTC, hmayenve commented on exec-files/exec-childhood-well-visit.js
> +//const patients = require('../data/patients/immunization/childhood-immunization-status-patients.json');
delete

2021-06-29 13:11 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +  case ("Initial Population")//and not "Denominator Exclusions")
it seems like it does not have any Denominator Exclusions so you can get rid of the commented part

2021-06-29 13:13 UTC, hmayenve commented on src/childhood-immunization-status.json
> +{
what is this file for?  i dont think it is needed

2021-06-29 13:14 UTC, hmayenve commented
hey @eawest2 i left a couple comments. Let me know what you think. It's looking good though 👍🏼

2021-06-29 13:23 UTC, hmayenve submitted a review, later dismissed
See the comments that I left

2021-06-30 13:42 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +	and AgeInMonthsAt(end of "Measurement Period")<= 15
According to the documentation, any age child below and up to 15 months old is correct. However, you're correct about plus 90 days, so I do need to increase the value to 18, not 15.

![image](https://user-images.githubusercontent.com/35747608/123970738-6304bf80-d987-11eb-95d6-c7eef8ff12cd.png)

2021-06-30 13:43 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +	and AgeInMonthsAt(end of "Measurement Period")<= 15
![image](https://user-images.githubusercontent.com/35747608/123970940-99423f00-d987-11eb-9cec-7ce71cd47227.png)

2021-06-30 14:04 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +    without [Encounter: "Primary Care Provider"] E1
Updated

2021-06-30 14:05 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +		//)
Updated.

2021-06-30 14:05 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +    where AgeInMonthsAt(E0.period.end) > 15
Updated.

2021-06-30 14:06 UTC, eawest2 commented on exec-files/exec-childhood-well-visit.js
> +//const patients = require('../data/patients/immunization/childhood-immunization-status-patients.json');
Updated.

2021-06-30 14:06 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +  case ("Initial Population")//and not "Denominator Exclusions")
Updated.

2021-06-30 14:07 UTC, eawest2 commented on src/childhood-immunization-status.json
> +{
Updated.

2021-06-30 18:23 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +	and AgeInMonthsAt(end of "Measurement Period")<= 15
I'm still not sure about this. Continuous Enrollment deals with Coverage because it is the minimum amount of time a member must be enrolled in an organization before becoming eligible for a measure. I think that for the CQL, we have to focus on what's under the `Eligible Population` so that being `Age` `Continuous Enrollment` etc.  and not the description which encompasses the whole measure. What do you think @JamesbZhu?

2021-06-30 18:26 UTC, hmayenve commented
@eawest2 I'm still getting a `getaddrinfo ENOTFOUND undefined` error when running it.

2021-07-01 17:29 UTC, JamesbZhu submitted a review, later dismissed
Great first piece of CQL! the logic looks good, i put in some comments about some small changes here and there.

2021-07-01 17:29 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +	and AgeInMonthsAt(end of "Measurement Period")<= 15
hmm, i think we'd want children who turn 15 months during the measurement period - if you put AgeInMonths(end of measurement period) <= 15, we wouldn't get kids who have turned 15 during the year. 

you would probably want to do something like `AgeInYears(start of measurement period) < 1 AND AgeInMonths(end of measurement period) >= 15`

2021-07-01 17:29 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +valueset "Primary Care Provider": '2.16.840.1.113762.1.4.1182.375'
not sure about this - more about this below

2021-07-01 17:29 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +    with [Encounter: "Primary Care Provider"] E1
not sure that we'd want to collect this. I took a look @ the code associated with this, and i don't think we're going to have an encounter with a code `PCP`. Instead i think we'd want to look at the PCP associated with this patient resource (https://www.hl7.org/fhir/patient.html). 

So it'd be something along the lines of `[Encounter: "well-care"] E0 with [Patient] P where exists(P.generalPractitioner)`

2021-07-01 17:29 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +		union DeduplicateBasedOnStartDate("Well-Care Without Duplicate Days")
i think we'd want to do an intersect here instead of union. Union would return a combined list of all 4 retrieves, where as an intersect (i think - you might need to fact check me on this) would return a filtered list with all 4 conditions being true

2021-07-01 17:29 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +  else Enc[0]
this seems really cool! I want to test this with some data but i probably won't get around to doing it today. I'll come back to this!

2021-07-01 17:43 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +  else Enc[0]
I think I stole this from Tyler? I'm not sure.

2021-07-01 18:19 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +		union DeduplicateBasedOnStartDate("Well-Care Without Duplicate Days")
Added.

2021-07-01 18:22 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +    with [Encounter: "Primary Care Provider"] E1
Added.

2021-07-01 18:23 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +valueset "Primary Care Provider": '2.16.840.1.113762.1.4.1182.375'
Resolved

2021-07-01 18:23 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +	and AgeInMonthsAt(end of "Measurement Period")<= 15
Alrighty, I'm outvoted. Implemented James' solution.

2021-07-08 13:56 UTC, hmayenve commented on data/patients/child-well-care/child-well-care-patients.json
> +    "resourceType": "Bundle",
@eawest2 as per our conversation with @JamesbZhu this morning please add more patient data for each numerator.

2021-07-08 13:56 UTC, hmayenve submitted a review, later dismissed
see the comment i left under patient data

2021-07-08 20:30 UTC, JamesbZhu submitted a review, later dismissed
LGTM, i would just suggest that we add enough patients to test all 7 numerators before merging

2021-07-09 13:37 UTC, eawest2 commented on data/patients/child-well-care/child-well-care-patients.json
> +    "resourceType": "Bundle",
The issue I run into is that this CQL throws an error when evaluating multiple patients, since it's in a single patient context. My understanding is that's how the data is supposed to be structured. Do you or @JamesbZhu have a template or model for how this is supposed to work?

2021-07-09 13:50 UTC, JamesbZhu commented on data/patients/child-well-care/child-well-care-patients.json
> +    "resourceType": "Bundle",
I believe if you set the `context Unfiltered` it should include all patients. but, in this case - you'd just need to add 6 more patients, one for each numerator category and check that the output for each individual patient is as expected. I don't think there's a need for evaluating multiple patients

2021-07-13 21:06 UTC, JamesbZhu submitted a review, later dismissed
I put in a couple comments, James and I ran into errors while compiling the new CQL to ELM - we can walk through some of this tomorrow if you've got time/and if you're feeling better.

2021-07-13 21:06 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +		)
This seems like it should be returning the encounters for all encounters that meet the 4 conditions, but i don't think i see that in the outputs. 
<img width="629" alt="Screen Shot 2021-07-13 at 4 59 34 PM" src="https://user-images.githubusercontent.com/19771231/125524262-db54777d-e041-4e57-bbb5-32a1bbbe8023.png">

2021-07-13 21:06 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +  end
this works perfectly

2021-07-21 18:19 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +      where exists(P.generalPractitioner)
implemented new method.

2021-07-26 21:27 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +    and E0.participant.individual.reference = P1.generalPractitioner.reference
should we be comparing the IDs of the PCP instead of just the reference? it seems to me like comparing the IDs is more accurate/reliable. what do you guys think @JamesbZhu @eawest2

2021-07-26 21:28 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +	Count(
I'm getting a lot of warnings when compiling it to elms. In order to clear the warning you have to remove the `Count()` here

2021-07-26 21:29 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +	case ( "Initial Population"
let's do `exists("Initial Population")`

2021-07-26 21:31 UTC, hmayenve commented on cql/well-child-visits-15-mos.cql
> +	and "Valid Visit Counter" = 0
let's also do `Count("Valid Visit Counter")`. Doing the above and this to all the numerators and denominators will get rid of all the warnings when compiling this cql to elms.

2021-07-26 21:33 UTC, hmayenve requested changes
This looks looks almost done. great job. I left some comments on some things i noticed. I think after that, this is in good shape.

2021-07-27 13:31 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +    and E0.participant.individual.reference = P1.generalPractitioner.reference
We actually tried this once, and it was ineffective. comparing the reference seems to work effectively.

2021-07-28 12:36 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +		)
still not seeing this, i think the expected behavior here is that we'd see 2 fhir objects (for this case) in each of the 4 welll-care outputs. 

consider using booleans (i.e. exists (well-care ...) AND exists (well-care ...) etc)

2021-07-28 12:38 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +    and E0.participant.individual.reference = P1.generalPractitioner.reference
i think both would work

2021-07-28 12:54 UTC, JamesbZhu reviewed
looks good! one final comment, and i think we should be good to merge.

2021-08-02 19:08 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +	case ( "Initial Population"
Implemented.

2021-08-02 19:08 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +	Count(
Implemented.

2021-08-02 19:08 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +	and "Valid Visit Counter" = 0
Implemented.

2021-08-02 19:08 UTC, hmayenve approved these changes
Great Job!

2021-08-02 19:08 UTC, eawest2 reviewed
Updated with final changes.

2021-08-03 15:54 UTC, JamesbZhu submitted a review, later dismissed
Last requests i promise. this should fix some issues, but i would test them and check the outputs to see if they're what you expected

2021-08-03 15:54 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +      such that exists(E2)
this doesn't seem to work very well, still getting an empty list with this. try this instead: 
```
define "Telehealth Encounter": 
  [Encounter: "Telehealth POS"] union [Encounter: "Telehealth Modifier"]

define "Well-Care Encounter Without Telehealth":
  [Encounter: "Well-Care"] 
    except "Telehealth Encounter"
```

2021-08-03 15:54 UTC, JamesbZhu commented on cql/well-child-visits-15-mos.cql
> +    where AgeInMonthsAt(E0.period.end) <= 15
```where AgeInMonthsAt(E0.period.end**.value**) <= 15```

adding a .value inside the AgeInMonthsAt() resulted in people showing up in the output for this expression

2021-08-03 17:29 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +      such that exists(E2)
Implemented

2021-08-03 17:30 UTC, eawest2 commented on cql/well-child-visits-15-mos.cql
> +    where AgeInMonthsAt(E0.period.end) <= 15
Implemented.

2021-08-03 17:32 UTC, JamesbZhu approved these changes

2021-08-03 17:33 UTC, merged