Diabetes Shared Library
amida-tech/saraswati-cql-execution pull request #24
Opened 2021-09-16 06:41 UTC by hmayenve

# Related Tickets

- [SAR-97](https://amida.atlassian.net/browse/SAR-97)

# How Things Worked (or Didn't) Before This PR

- Diabetes BP cql and Diabetes A1C share a lot of the same logic and are in different files.

# How Things Work Now (And How to Test)

- There is a common library that contains the logic and is used by both cql files for BP and A1C. The expressions remain the same since we need them for saraswati reports.
### How to Test
- Checkout this branch
- Run `Yarn Start`
- In another terminal run `node receiver.js `
- Then modify (ie. add a space and save) the `cdc_hba1c-patients.json` data file and then the `cdc_diabetes-bp-patients.json` data file. The results should be exactly the same as if you where to run this same steps in the `develop` branch

2021-09-17 13:08 UTC, eawest2 approved these changes
Everything seems in order. Good job.

2021-09-20 15:08 UTC, jmfadeley requested changes
@hmayenve something seems to go wrong with Diabetes BP. HbA1c works fine, with the only difference being the timestamp. But in BP, there's a difference between `develop` and this branch:

![image](https://user-images.githubusercontent.com/4026454/134026258-0b06e02b-8c8d-4da3-bc0d-ecbe822f83f7.png)

This could be a fluke, but I tested twice and got the same results. Can you take a look and make sure something on Diabetes BP wasn't lost in translation?

2021-09-20 16:33 UTC, jmfadeley approved these changes

2021-09-20 16:33 UTC, jmfadeley commented
@hmayenve good to go.

2021-09-20 16:36 UTC, merged