Feature/sar 311 js backward compatibility
amida-tech/saraswati-cql-execution pull request #42
Opened 2021-11-19 16:38 UTC by jmfadeley

# Related Tickets

- [SAR-###](https://jira.amida-tech.com/browse/SAR-###)

# Other Repos' PR(s) Intended to Work With This PR

- LINK_TO_THE_PR or "None."

# How Things Worked (or Didn't) Before This PR

# How Things Work Now (And How to Test)

# Readiness

1. [ ] This PR passes all automated tests.
2. [ ] This PR has no linting errors.
3. [ ] This PR's changes to configuration files have been documented in all appropriate places (such as but not limited to README.md), if applicable.

2021-12-01 17:43 UTC, hmayenve commented on config.js
> +if (process.env.NODE_ENV.trim() === 'test') {
Im getting the following error.
<img width="734" alt="Screen Shot 2021-12-01 at 12 37 59 PM" src="https://user-images.githubusercontent.com/39383117/144284998-de89af4a-ca58-4ee9-9349-f19b96c36cd8.png">
r

I am not sure why `process.env.NODE_ENV` is `undefined` since I have that variable set in my `.env`

2021-12-01 18:32 UTC, anthem123 commented on config.js
> +if (process.env.NODE_ENV.trim() === 'test') {
It looks like the code is trying to check the environment variable NODE_ENV to determine which if it should load `.env` or `.env.test`. But since neither file has been loaded there are no environment variables to check.

I found out you can set it in the command to start the node process. The 2 commands below worked for me.

`NODE_ENV=test node processor-kafka.js` or `NODE_ENV=test node processor.js`

2021-12-01 18:55 UTC, hmayenve commented on config.js
> +if (process.env.NODE_ENV.trim() === 'test') {
got it. thanks

2021-12-01 19:16 UTC, hmayenve requested changes
Let make the change the script in package.json to include `NODE_ENV=test node processor.js` or figure out a way for it to not fail when determining which if it should load .env or .env.test

Everything else looks good and works as intended

2021-12-02 16:32 UTC, hmayenve approved these changes

2021-12-02 17:12 UTC, merged